name: Update Usernames Weekly
on:
  schedule:
    - cron: "45 23 * * 6"
jobs:
  update-usernames:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: name: Install lxml
        run: pip install lxml
      - name: Run fetch_usernames_regularly.py
        run: python fetch_usernames_regularly.py
      - name: Commit and push changes
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add usernames.txt
          git commit -m "Auto update usernames.txt" || echo "No changes to commit"
          git push origin main
